name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: appdeploy

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)


 
    - run: docker build -f Dockerfilehub . -tag selenium-hub
        
 
    
    # Create namespace if doesn't exist
    - run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -

# ##Selenium Hub Application Deployment####

    - uses: azure/k8s-deploy@v1
      with:
        manifests:
          appdeploy/manifests/sele-hub.yml

# ##Selenium Node Application Deployment####

    - uses: azure/k8s-deploy@v1
      with:
        manifests:
          appdeploy/manifests/sele-node.yml


#      with:
#        version: '1.22.0'
